GET http://localhost:3000/event


###

GET http://localhost:3000/event/625880ab8740afb90a5bcc84

###

POST http://localhost:3000/event
Content-Type: application/json

{
    "name":"Afternoon Walk",
    "type":"Walk",
    "dueDate": "2022-05-22T19:31:14Z",
    "repeatDays": "MWF"
}

###

DELETE http://localhost:3000/event/623d0b1ac72a39ad4d809079

###

PATCH http://localhost:3000/event/6258afe3f53a7849274d1507
Content-Type: application/json


{
    "completed": false
}
