GET http://localhost:3000/event


###

GET http://localhost:3000/event/623ab5198c0c6b13ea08fa6a

###

POST http://localhost:3000/event
Content-Type: application/json

{
    "name":"Gym time",
    "type":"Weight Training",
    "dueDate": "2022-02-22T19:31:14Z",
    "repeatDays": "MWF"
}

###

DELETE http://localhost:3000/event/623b6a630a677d152bfa523b

###

PATCH http://localhost:3000/event/623b6a74bc2e789ea204fce8
Content-Type: application/json

{
    "repeatDays":"MW"
}